services:
  otel-datadog:
    image: datadog/agent:latest
    pid: host
    ports:
      - "5000:5000"
      - "5003:5003"
      - "8125:8125"
      - "6162:6162"
      - "8126:8126"
      - "4317:4317"
      - "4318:4318"
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
